# Docker-specific application configuration
server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: api-best-practices
  
  # Disable Redis-related auto-configurations
  autoconfigure:
    exclude:
      - org.redisson.spring.starter.RedissonAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
  
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/api_best_practices}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:badsha@123}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 100
        order_inserts: true
        order_updates: true
  
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  
  redis:
    host: ${SPRING_REDIS_HOST:redis}
    port: ${SPRING_REDIS_PORT:6379}
    password: ${SPRING_REDIS_PASSWORD:redis123}
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER_URI:}
          jwk-set-uri: ${OAUTH2_JWK_SET_URI:}

# Application-specific configuration
app:
  security:
    jwt:
      secret: ${JWT_SECRET:mySecretKey12345678901234567890123456789012345678901234567890}
      expiration: 86400000 # 24 hours in milliseconds
      refresh-expiration: 604800000 # 7 days in milliseconds
  
  rate-limit:
    enabled: ${APP_RATE_LIMIT_ENABLED:true}
    requests-per-minute: ${APP_RATE_LIMIT_REQUESTS_PER_MINUTE:100}
    burst-capacity: 200
    refill-tokens: 100
    refill-period: 60 # seconds
  
  idempotency:
    enabled: ${APP_IDEMPOTENCY_ENABLED:true}
    key-header: Idempotency-Key
    ttl-hours: ${APP_IDEMPOTENCY_TTL_HOURS:24}
  
  pagination:
    default-page-size: 20
    max-page-size: 100
  
  api:
    version: v1
    base-path: /api/v1

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    displayRequestDuration: true
    displayOperationId: true
    showExtensions: true
    showCommonExtensions: true
  show-actuator: true
  group-configs:
    - group: 'all'
      display-name: 'All APIs'
      paths-to-match: '/**'

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.example.apibestpractices: INFO
    org.springframework.security: WARN
    org.springframework.web: WARN
    org.springframework.data.redis: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: /app/logs/application.log
