# Local development configuration without Redis
server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: api-best-practices
  
  datasource:
    url: jdbc:postgresql://localhost:5432/api_best_practices
    username: postgres
    password: badsha@123
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 100
        order_inserts: true
        order_updates: true
  
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  
  # Disable Redis for local development
  redis:
    host: localhost
    port: 6379
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER_URI:}
          jwk-set-uri: ${OAUTH2_JWK_SET_URI:}

# Application-specific configuration
app:
  security:
    jwt:
      secret: ${JWT_SECRET:mySecretKey12345678901234567890123456789012345678901234567890}
      expiration: 86400000 # 24 hours in milliseconds
      refresh-expiration: 604800000 # 7 days in milliseconds
  
  # Disable rate limiting for local development
  rate-limit:
    enabled: false
    requests-per-minute: 100
    burst-capacity: 200
    refill-tokens: 100
    refill-period: 60 # seconds
  
  # Disable idempotency for local development
  idempotency:
    enabled: false
    key-header: Idempotency-Key
    ttl-hours: 24
  
  pagination:
    default-page-size: 20
    max-page-size: 100
  
  api:
    version: v1
    base-path: /api/v1

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    displayRequestDuration: true
    displayOperationId: true
    showExtensions: true
    showCommonExtensions: true
  show-actuator: true
  group-configs:
    - group: 'all'
      display-name: 'All APIs'
      paths-to-match: '/**'

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.example.apibestpractices: DEBUG
    org.springframework.security: INFO
    org.springframework.web: INFO
    org.springframework.data.redis: WARN
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
