spring:
  application:
    name: redis-advanced-demo
  
  datasource:
    url: jdbc:postgresql://localhost:5432/redis_demo
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  cache:
    type: redis
    redis:
      time-to-live: 600000 # 10 minutes
  
  redis:
    host: localhost
    port: 6379
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  
  session:
    store-type: redis
    redis:
      namespace: spring:session
      flush-mode: on_save
  
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

server:
  port: 8080

logging:
  level:
    com.example.redis: DEBUG
    org.springframework.cache: DEBUG
    org.springframework.session: DEBUG
