services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: api-best-practices-postgres
    environment:
      POSTGRES_DB: api_best_practices
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: badsha@123
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - api-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d api_best_practices"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Redis Cache (temporarily disabled)
  # redis:
  #   image: redis:7-alpine
  #   container_name: api-best-practices-redis
  #   command: redis-server --appendonly yes --requirepass redis123
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   networks:
  #     - api-network
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #   restart: unless-stopped

  # API Best Practices Application
  api-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-best-practices-app
    environment:
      # Database Configuration
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/api_best_practices
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: badsha@123
      
      # Redis Configuration
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_REDIS_PASSWORD: redis123
      
      # JWT Configuration
      JWT_SECRET: mySecretKey12345678901234567890123456789012345678901234567890
      
      # Application Configuration
      SERVER_PORT: 8080
      SPRING_PROFILES_ACTIVE: docker
      
      # Logging Configuration
      LOGGING_LEVEL_COM_EXAMPLE_APIBESTPRACTICES: INFO
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: WARN
      LOGGING_LEVEL_ORG_HIBERNATE_SQL: WARN
      
      # Rate Limiting
      APP_RATE_LIMIT_ENABLED: "false"
      APP_RATE_LIMIT_REQUESTS_PER_MINUTE: "100"
      
      # Idempotency
      APP_IDEMPOTENCY_ENABLED: "false"
      APP_IDEMPOTENCY_TTL_HOURS: "24"
    ports:
      - "8080:8080"
    networks:
      - api-network
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: api-best-practices-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    networks:
      - api-network
    depends_on:
      - api-app
    restart: unless-stopped
    profiles:
      - production

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  api-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
